// apps/angular/src/hour-markers/hour-markers.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, input } from '@angular/core';
import { eachHourOfInterval, endOfDay, startOfDay } from 'date-fns';

@Component({
  selector: 'app-hour-markers',
  templateUrl: './hour-markers.component.html',
  imports: [CommonModule],
})
export class HourMarkersComponent {
  date = input.required<Date>();

  hours = computed(() =>
    eachHourOfInterval({
      start: startOfDay(this.date()),
      end: endOfDay(this.date()),
    }).slice(1)
  );
}

// apps/react-calendar/src/day-or-week-view/hour-markers.tsx
import {
  eachHourOfInterval,
  endOfDay,
  format,
  Locale,
  startOfDay,
} from 'date-fns'

export interface HourMarkersProps {
  date: Date | number
  locale?: Locale
}

export function HourMarkers(props: HourMarkersProps) {
  const hours = eachHourOfInterval({
    start: startOfDay(props.date),
    end: endOfDay(props.date),
  })

  return (
    <div>
      {hours.slice(1).map(hour => (
        <div
          className="relative text-xs tabular-nums text-neutral-600 h-12 w-20 text-right dark:text-neutral-300"
          key={hour.toISOString()}
        >
          <div className="absolute -top-2 right-0 px-2">
            {format(hour, 'p', { locale: props.locale })}
          </div>
        </div>
      ))}
    </div>
  )
}
