// apps/angular/src/app/app.component.ts
import { Component, signal } from '@angular/core'
import { HasStartAndEndDate } from '@calendar-ui/core'
import {
  DayOrWeekViewType,
  Event,
  DayOrWeekViewComponent,
} from '../day-or-week-view/day-or-week-view.component'
import { ProjectBannerComponent } from '../project-banner/project-banner.component'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  imports: [DayOrWeekViewComponent, ProjectBannerComponent],
})
export class AppComponent {
  viewingDate = signal(new Date())
  view = signal<DayOrWeekViewType>(window.innerWidth < 768 ? 'day' : 'week')
  selectedEventId = signal<string | undefined>(undefined)
  events = signal<Event[]>([])

  handleChangeViewingDate(viewingDate: Date) {
    this.viewingDate.set(viewingDate)
  }

  handleChangeView(view: DayOrWeekViewType) {
    this.view.set(view)
  }

  handleEventClick(eventId: string) {
    this.selectedEventId.set(eventId)
  }

  handleSelectEvent(selectedEventId: string | undefined) {
    this.selectedEventId.set(selectedEventId)
  }

  handleChangeEvents(events: Event[]) {
    this.events.set(events)
  }

  handleSketchEvent(sketch: HasStartAndEndDate) {
    const id = Math.random().toString()
    this.events.update(events => [...events, { id, ...sketch }])
    this.selectedEventId.set(id)
  }
}

<app-project-banner />

<app-day-or-week-view
  [viewingDate]="viewingDate()"
  [view]="view()"
  [events]="events()"
  [selectedEventId]="selectedEventId()"
  [weekStartsOn]="1"
  (changeEvents)="handleChangeEvents($event)"
  (changeView)="handleChangeView($event)"
  (changeViewingDate)="handleChangeViewingDate($event)"
  (selectEvent)="handleSelectEvent($event)"
  (sketchEvent)="handleSketchEvent($event)"
/>

// apps/react/src/app.tsx
import { DayOrWeekView, DayOrWeekViewType, Event } from './day-or-week-view'
import { useState } from 'react'
import { ProjectBanner } from './project-banner'

export function App() {
  const [viewingDate, setViewingDate] = useState(new Date())
  const [view, setView] = useState<DayOrWeekViewType>(
    window.innerWidth < 768 ? 'day' : 'week'
  )

  const [selectedEventId, setSelectedEventId] = useState<string>()
  const [events, setEvents] = useState<Event[]>([])

  return (
    <>
      <ProjectBanner />

      <DayOrWeekView
        viewingDate={viewingDate}
        onChangeViewingDate={setViewingDate}
        weekStartsOn={1}
        view={view}
        events={events}
        onChangeView={setView}
        selectedEventId={selectedEventId}
        onEventSelected={setSelectedEventId}
        onEventsChange={setEvents}
        onEventSketched={sketch => {
          const id = Math.random().toString()
          setEvents([...events, { id, ...sketch }])
          setSelectedEventId(id)
        }}
      />
    </>
  )
}
