// apps/angular/src/current-hour-marker/current-hour-marker.component.ts
import { Component, computed, DestroyRef, inject, signal } from '@angular/core'

@Component({
  selector: 'app-current-hour-marker',
  templateUrl: './current-hour-marker.component.html',
})
export class CurrentHourMarkerComponent {
  private destroyRef = inject(DestroyRef)
  private now = signal(new Date())

  constructor() {
    const interval = setInterval(() => {
      this.now.set(new Date())
    }, 1000)

    this.destroyRef.onDestroy(() => clearInterval(interval))
  }

  private minutesPassedToday = computed(
    () => this.now().getHours() * 60 + this.now().getMinutes()
  )

  top = computed(() => `${(this.minutesPassedToday() / 1440) * 100}%`)
}

<div
  class="absolute left-0 right-0 h-[2px] bg-rose-500 z-20 pointer-events-none dark:bg-rose-400"
  [style.top]="top()"
>
  <div
    class="absolute -top-[5px] -left-[6px] w-[12px] h-[12px] bg-rose-500 rounded-full dark:bg-rose-400"
  ></div>
</div>

// src/day-or-week-view/current-hour-marker.tsx
import { useEffect, useState } from 'react'

export function CurrentHourMarker() {
  const [now, setNow] = useState(new Date())

  useEffect(() => {
    const interval = setInterval(() => {
      setNow(new Date())
    }, 1000)
    return () => clearInterval(interval)
  }, [])

  const minutesPassedToday = now.getHours() * 60 + now.getMinutes()

  return (
    <div
      className="absolute top-0 left-0 right-0 h-[2px] bg-red-500 z-20 pointer-events-none dark:bg-red-400"
      style={{
        top: `${(minutesPassedToday / 1440) * 100}%`,
      }}
    >
      <div className="absolute -top-[5px] -left-[6px] w-[12px] h-[12px] bg-red-500 rounded-full dark:bg-red-400" />
    </div>
  )
}
