// apps/angular-calendar/src/event-area-grid/event-area-grid.component.ts
import { Component, input } from '@angular/core';

@Component({
  selector: 'app-event-area-grid',
  templateUrl: './event-area-grid.component.html',
  host: { class: 'flex w-full' },
})
export class EventAreaGridComponent {
  days = input<number>(1);
  hours = input<number>(24);

  arrayOfLength(length: number): number[] {
    return Array.from({ length }, (_, i) => i);
  }
}

@for (x of arrayOfLength(days()); track x) {
<div class="basis-0 grow">
  @for (x of arrayOfLength(hours()); track x) {
  <div
    class="border-b border-l border-black/15 h-12 dark:border-white/15"
  ></div>
  }
</div>
}

// src/day-or-week-view/event-area-grid.tsx
export interface EventAreaGridProps {
  days: number
  hours: number
}

export function EventAreaGrid(props: EventAreaGridProps) {
  return (
    <>
      {Array.from({ length: props.days }).map((_, count) => (
        <div className="basis-0 grow" key={count}>
          {Array.from({ length: props.hours }).map((_, count) => (
            <div
              className="border-b border-l border-black/15 h-12 dark:border-white/15"
              key={count}
            />
          ))}
        </div>
      ))}
    </>
  )
}
