// apps/angular/src/event-area-grid/event-area-grid.component.ts
import { Component, input } from '@angular/core'
import { addDays, isToday } from 'date-fns'
import { CurrentHourMarkerComponent } from '../current-hour-marker/current-hour-marker.component'

@Component({
  selector: 'app-event-area-grid',
  templateUrl: './event-area-grid.component.html',
  host: { class: 'flex w-full' },
  imports: [CurrentHourMarkerComponent],
})
export class EventAreaGridComponent {
  start = input.required<Date>()
  days = input<number>(1)
  hours = input<number>(24)

  arrayOfLength(length: number): number[] {
    return Array.from({ length }, (_, i) => i)
  }

  isCurrentDay(index: number): boolean {
    const day = addDays(this.start(), index)
    return isToday(day)
  }
}

@for (x of arrayOfLength(days()); track x) {
<div class="relative basis-0 grow">
  @for (x of arrayOfLength(hours()); track x) {
  <div
    class="border-b border-l border-black/15 h-12 dark:border-white/15"
  ></div>
  } @if (isCurrentDay(x)) {
  <app-current-hour-marker />
  }
</div>
}

// apps/react/src/day-or-week-view/event-area-grid.tsx
import { addDays, isToday } from 'date-fns'
import { CurrentHourMarker } from './current-hour-marker'

export interface EventAreaGridProps {
  start: Date
  days: number
  hours: number
}

export function EventAreaGrid(props: EventAreaGridProps) {
  return (
    <>
      {Array.from({ length: props.days }).map((_, count) => {
        const day = addDays(props.start, count)
        return (
          <div className="relative basis-0 grow" key={count}>
            {Array.from({ length: props.hours }).map((_, count) => (
              <div
                className="border-b border-l border-black/15 h-12 dark:border-white/15"
                key={count}
              />
            ))}

            {isToday(day) && <CurrentHourMarker />}
          </div>
        )
      })}
    </>
  )
}
